import turtle
turtle.bgcolor('blue')
t = turtle.Turtle()
t.begin_fill()
t.color('gray')
for i in range(4):
    t.forward(100)
    t.left(90)
t.end_fill()
t.penup()
t.goto(-20,100)
t.pendown()
t.begin_fill()
t.color('red')
t.left(60)
t.forward(140)
t.right(120)
t.forward(140)
t.right(120)
t.forward(140)
t.end_fill()
t.penup()
t.goto(25,80)
t.begin_fill()
t.pendown()
t.color('yellow')
for i in range(4):
    t.forward(20)
    t.left(90)
t.end_fill()
t.hideturtle()
